export const defaultBooks = [
    {
        "title": "Samantar",
        "author": "Suhas Shirvalkar",
        "price": 210,
        "category": "Fiction",
        "stock": 5,
        "image": "https://www.bookganga.com/eBooks/Content/images/books/584a53123264450a97cea46ce8529b61.jpg",
        "description": "Samantar by Suhas Shirvalkar is a Marathi novel about a man who discovers another person living a life parallel to his own, exploring fate, destiny, and the mysterious connections between two lives.",
        "pages": 196,
        "language": "Marathi",
        "publicationDate": "1990-01-15",
        "id": "FICSAM1773292550490"
    },
    {
        "title": "Duniyadari",
        "author": "Suhas Shirvalkar",
        "price": 263,
        "category": "Comics & Graphic Novels",
        "stock": 10,
        "image": "https://www.bookganga.com/eBooks/Content/images/books/adb7943c377848d693323ffa22549f4c.jpg",
        "description": "A nostalgic college-life story following Shreyas and his friends as they experience friendship, love, heartbreak, and growing up, revealing how relationships and choices shape their journey into adulthood.",
        "pages": 256,
        "language": "Marathi",
        "publicationDate": "2000-03-18",
        "id": "COMDUN1773292649434"
    },
    {
        "title": "Radha",
        "author": "Samar Sarpotdar",
        "price": 218,
        "category": "Children",
        "stock": 4,
        "image": "https://www.bookganga.com/eBooks/Content/images/books/ed7bcdf1ac5d499c9ed34da50c4b8329.jpg",
        "description": "A touching love story about Radha, exploring deep emotions, devotion, and sacrifice as she navigates relationships, personal struggles, and the meaning of true love in life.",
        "pages": 145,
        "language": "Marathi",
        "publicationDate": "2013-06-19",
        "id": "CHIRAD1773292992512"
    },
    {
        "title": "Atomic Habits",
        "author": "James Clear",
        "price": 499,
        "category": "Self-Help",
        "stock": 25,
        "image": "https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg",
        "description": "A practical guide on how tiny habits can lead to remarkable results. It explains how small improvements build powerful long-term change.",
        "pages": 320,
        "language": "English",
        "publicationDate": "2018-10-16",
        "id": "SELATO1773293246672"
    },
    {
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "price": 350,
        "category": "Fiction",
        "stock": 30,
        "image": "https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL.jpg",
        "description": "A philosophical novel about a shepherd named Santiago who travels in search of treasure. The story teaches about dreams and destiny.",
        "pages": 208,
        "language": "English",
        "publicationDate": "1988-01-05",
        "id": "FICTHE1773293291213"
    },
    {
        "title": "Ikigai",
        "author": "Hector Garcia",
        "price": 399,
        "category": "Self-Help",
        "stock": 18,
        "image": "https://images-na.ssl-images-amazon.com/images/I/81l3rZK4lnL.jpg",
        "description": "Explores the Japanese concept of finding purpose in life. It combines philosophy, longevity, and happiness.",
        "pages": 208,
        "language": "English",
        "publicationDate": "2016-08-29",
        "id": "SELIKI1773293332735"
    },
    {
        "title": "Rich Dad Poor Dad",
        "author": "Robert T. Kiyosaki",
        "price": 450,
        "category": "Business & Finance",
        "stock": 22,
        "image": "https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg",
        "description": "Explains financial literacy and wealth building through the lessons of two father figures. A classic book on money mindset.",
        "pages": 336,
        "language": "English",
        "publicationDate": "1974-01-04",
        "id": "BUSRIC1773293392852"
    },
    {
        "title": "The Psychology of Money",
        "author": "Morgan Housel",
        "price": 420,
        "category": "Business & Finance",
        "stock": 20,
        "image": "https://images-na.ssl-images-amazon.com/images/I/81Lb75rUhLL.jpg",
        "description": "Explains how people behave with money rather than how they should behave. It shows how emotions influence financial decisions.",
        "pages": 256,
        "language": "English",
        "publicationDate": "2020-08-09",
        "id": "BUSTHE1773293430220"
    },
    {
        "title": "Harry Potter and the Sorcerer's Stone",
        "author": "J. K. Rowling",
        "price": 550,
        "category": "Fiction",
        "stock": 12,
        "image": "https://images-na.ssl-images-amazon.com/images/I/81YOuOGFCJL.jpg",
        "description": "The first book in the Harry Potter series where a young wizard discovers his magical heritage and attends Hogwarts School.",
        "pages": 309,
        "language": "English",
        "publicationDate": "1997-06-26",
        "id": "FICHAR1773293474544"
    },
    {
        "title": "Shyamchi Aai",
        "author": "Sane Guruji",
        "price": 250,
        "category": "Children",
        "stock": 20,
        "image": "https://www.bookganga.com/eBooks/Content/images/books/7b217fb335e64dab95dd294db7e24083.jpg",
        "description": "A touching Marathi classic describing the deep bond between a mother and her son. The book highlights moral values, love, and sacrifice.",
        "pages": 192,
        "language": "Marathi",
        "publicationDate": "1933-01-01",
        "id": "CHISHY1773293591385"
    },
    {
        "title": "Mrityunjay",
        "author": "Shivaji Sawant",
        "price": 450,
        "category": "Children",
        "stock": 15,
        "image": "https://rukminim2.flixcart.com/image/480/640/kusph8w0/regionalbooks/l/y/n/mrutyunjay-kadambari-by-shivaji-sawant-in-marathi-original-imag7ujhfkkvx4c9.jpeg?q=90",
        "description": "A powerful retelling of the life of Karna from the Mahabharata. The novel explores courage, loyalty, and destiny.",
        "pages": 704,
        "language": "Marathi",
        "publicationDate": "1967-01-01",
        "id": "CHIMRI1773293685557"
    },
    {
        "title": "Batatyachi Chaal",
        "author": "P. L. Deshpande",
        "price": 300,
        "category": "Children",
        "stock": 18,
        "image": "https://rukminim2.flixcart.com/image/480/640/kidgnm80-0/regionalbooks/t/n/p/batatyachi-chal-original-imafy6g6ztvkd3qf.jpeg?q=90",
        "description": "A humorous Marathi book portraying the life and characters living in a chawl. It beautifully captures everyday middle-class life.",
        "pages": 180,
        "language": "Marathi",
        "publicationDate": "1958-01-01",
        "id": "CHIBAT1773293752499"
    },
    {
        "title": "Gunahon Ka Devta",
        "author": "Dharamvir Bharati",
        "price": 320,
        "category": "Other",
        "stock": 16,
        "image": "https://www.bookganga.com/eBooks/Content/images/books/fc570b2d19f646b581f70498e973e9b6.jpg",
        "description": "A famous Hindi romantic novel about love, sacrifice, and emotions between Chandar and Sudha. It is considered a classic in Hindi literature.",
        "pages": 264,
        "language": "Hindi",
        "publicationDate": "1949-01-01",
        "id": "OTHGUN1773293821023"
    },
    {
        "title": "Zero to One",
        "author": "Peter Thiel",
        "price": 150,
        "category": "Business & Finance",
        "stock": 14,
        "image": "https://images-na.ssl-images-amazon.com/images/I/71m-MxdJ2WL.jpg",
        "description": "Explains how startups build innovative businesses by creating something new rather than competing in existing markets.",
        "pages": 224,
        "language": "English",
        "publicationDate": "2014-09-19",
        "id": "BUSZER1773293976058"
    },
    {
        "title": "The Lean Startup",
        "author": "Eric Ries",
        "price": 520,
        "category": "Business & Finance",
        "stock": 18,
        "image": "https://images-na.ssl-images-amazon.com/images/I/81-QB7nDh4L.jpg",
        "description": "A guide for entrepreneurs on building startups efficiently by testing ideas quickly and learning from customer feedback.",
        "pages": 336,
        "language": "English",
        "publicationDate": "2011-12-20",
        "id": "BUSTHE1773294025624"
    },
    {
        "title": "One Up On Wall Street",
        "author": "Peter Lynch",
        "price": 430,
        "category": "Business & Finance",
        "stock": 20,
        "image": "https://m.media-amazon.com/images/I/41euB0HUqIL._AC_UF1000,1000_QL80_.jpg",
        "description": "A famous investment book that explains how everyday investors can identify profitable stocks before professional investors.",
        "pages": 304,
        "language": "English",
        "publicationDate": "1989-03-04",
        "id": "BUSONE1773294093641"
    },
    {
        "title": "The 4-Hour Workweek",
        "author": "Timothy Ferriss",
        "price": 480,
        "category": "Business & Finance",
        "stock": 16,
        "image": "https://m.media-amazon.com/images/S/aplus-media/vc/518de9cb-c3e4-4333-a846-206bf3cd6a6a.__CR0,0,300,300_PT0_SX300_V1___.jpg",
        "description": "Teaches how to escape the traditional 9–5 job, build automated income streams, and design a flexible lifestyle.",
        "pages": 416,
        "language": "English",
        "publicationDate": "2007-04-24",
        "id": "BUSTHE1773294168980"
    },
    {
        "title": "Watchmen",
        "author": "Alan Moore",
        "price": 199,
        "category": "Comics & Graphic Novels",
        "stock": 0,
        "image": "https://m.media-amazon.com/images/I/81U7nh6OPVL._AC_UF1000,1000_QL80_.jpg",
        "description": "A dark and complex superhero graphic novel that explores morality, politics, and human nature. It is considered one of the greatest graphic novels ever written.",
        "pages": 416,
        "language": "English",
        "publicationDate": "1987-09-01",
        "id": "COMWAT1773316308778"
    },
    {
        "title": "One Piece",
        "author": "Eiichiro Oda",
        "price": 420,
        "category": "Comics & Graphic Novels",
        "stock": 0,
        "image": "https://m.media-amazon.com/images/I/81IgOp0fOiL._UF1000,1000_QL80_.jpg",
        "description": "Monkey D. Luffy begins his journey to become the Pirate King and sets sail to find the legendary treasure called One Piece.",
        "pages": 208,
        "language": "English",
        "publicationDate": "1997-12-24",
        "id": "COMONE1773317012229"
    }
]